services:
  tracker:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: python main.py
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    restart: unless-stopped
